---
#
# Gitlab CI file for building the NginX container
# and deploying it someplace.
#

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

build_container:
  stage: build
  image: registry.duvall.org.uk/docker1/docker-in-docker:20.10.5-dind
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
    - when: never
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - |
      docker build \
        --network host \
        -t "$CI_REGISTRY_IMAGE"":""$CI_BUILD_REF_SLUG" \
        -f Dockerfile \
        .
    - docker push "$CI_REGISTRY_IMAGE"":""$CI_BUILD_REF_SLUG"

deploy_container:
  stage: deploy
  image: alpine
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
    - when: never
  script:
    - echo "Hello, world"
