apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: app
spec:
  rules:
  - host: exam-app.stage.duvall.org.uk
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: http
