apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: exam-app
  name: app
  namespace: exam
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: exam-app
  sessionAffinity: None
  type: ClusterIP
